### ISSUE TITLE
Wutond cypher 

### ISSUE THREAD

**Issue by felice11** [songlink/docs#1]
https://song.link/s/3YtuseMDlgRyO6qVabXMjG 
this link is missing the official YouTube video which is this one
https://youtu.be/1DaxSLsPN84

how can I solve this problem?

**Comment by kweiberth** [comment]
I've updated it for you so the official video should be showing up now

**Comment by felice11** [comment]
Grazie mille

Il giorno gio 18 lug 2019 alle 17:57 Kurt Weiberth <notifications@github.com>
ha scritto:

**Comment by felice11** [comment]
( https://u15586970.ct.sendgrid.net/ls/click?upn=942-2F81YTq4FCz86XCgCDC124e5CLMBNlIeS0pA7lbbVcEI31WzO-2FCF5LsEW2mjEc-2FacnFaPwO2XMSCetXATMcBISqCT5qENC1PzWaGNArb9ttnR1qvGKflBLNRAjXvUZppVM_U31jt5HgHBh7k3Grc5s4lw4ob-2Fr0yRdKsaHlSRHdR0SwB3KR7nD5ra5PLCuSKMFyMWOSVNZ25EYqr0028Prr7uwby-2FfIWCDzGQ20p8t539FVTvXo4Pm2VopMdyfdVOXH5xZbYSp1GdRCIGFMYoo3RfjxGbJcoaVh6cU-2F2SuUf9ZdMOPyQk7yCwZeytbpstd8L-2F9TRF-2Fv4mEArEytEzF45jOCIuojeaZwuhRmK5G9-2F-2BZfeH4Q-2B0poiDHkVCaBUsGT2FatMGMfSjbQpwFfX907rxnZ4q8eJEgLEKNVv1Ng-2BDN2-2BRpe4irC3GMzm-2FghYJEgoHxFNtSRa6SgRd44TdneVZaGIKn57AQ96Orka-2B3EdfARY0TaIMdJpBxFHLmFqQobZhUPZFUwpBJ91Zy-2Fyg-2BlqW6ZVmH7MjPoMkJYXqdK0L2m8kSl6nBXpCcKZORq1EaV )

Ciao,

songlink/docs  ti ha invitato a registrarti per condividere insieme i vostri servizi preferiti.

Ti basta cliccare qui ( https://u15586970.ct.sendgrid.net/ls/click?upn=942-2F81YTq4FCz86XCgCDC124e5CLMBNlIeS0pA7lbbUdruqZstpxZUXrJLZGf8BCnpHJ_U31jt5HgHBh7k3Grc5s4lw4ob-2Fr0yRdKsaHlSRHdR0SwB3KR7nD5ra5PLCuSKMFyMWOSVNZ25EYqr0028Prr7uwby-2FfIWCDzGQ20p8t539FVTvXo4Pm2VopMdyfdVOXH5xZbYSp1GdRCIGFMYoo3RfjxGbJcoaVh6cU-2F2SuUf9ZdMOPyQk7yCwZeytbpstd8L-2F9TRF-2Fv4mEArEytEzF45jOCIuojeaZwuhRmK5G9-2F-2BZfeH4Q-2B0poiDHkVCaBUsGT2FatMGMfSjbQpwFfX907rxnZ4q8eJEgLEKNVv1Ng-2BDOnlfs8sEQGNhuzi3mwwD8k2vHw1R-2F3BRH6-2FV55kNLWoNir5agN-2FHq8r7r4aukZMZv7u5jHI0ulqoVR4SFcDCc3brWdJpOHN8j9FNRBOxttmD2iy5HzMuIp1GfQFWe2vfmH1D61aAitO3e-2F25NQEtnX ) per scoprire di più.

REGISTRATI ( https://u15586970.ct.sendgrid.net/ls/click?upn=942-2F81YTq4FCz86XCgCDC124e5CLMBNlIeS0pA7lbbUdruqZstpxZUXrJLZGf8BC1Fs2_U31jt5HgHBh7k3Grc5s4lw4ob-2Fr0yRdKsaHlSRHdR0SwB3KR7nD5ra5PLCuSKMFyMWOSVNZ25EYqr0028Prr7uwby-2FfIWCDzGQ20p8t539FVTvXo4Pm2VopMdyfdVOXH5xZbYSp1GdRCIGFMYoo3RfjxGbJcoaVh6cU-2F2SuUf9ZdMOPyQk7yCwZeytbpstd8L-2F9TRF-2Fv4mEArEytEzF45jOCIuojeaZwuhRmK5G9-2F-2BZfeH4Q-2B0poiDHkVCaBUsGT2FatMGMfSjbQpwFfX907rxnZ4q8eJEgLEKNVv1Ng-2BDNczQdte3bt6YW-2BFGYog-2BNTT8GU0J-2FG1Ri8bdL2-2BCcITHhmjHijf5gf0QlsfxcBBHfqZznhpLoRYX4JuRvlfeCein6R2vIIUd4yojo46qHUpv-2BPE2FeoJqv4cRR2wz7BRhge-2FTBhdSo6QXDisjia6ot )

Come funziona:
* Scegli i tuoi servizi preferiti
* Inizia a condividere
* Goditi i tuoi servizi

SCOPRI DI PIÙ ( https://u15586970.ct.sendgrid.net/ls/click?upn=942-2F81YTq4FCz86XCgCDC124e5CLMBNlIeS0pA7lbbUdruqZstpxZUXrJLZGf8BCzCGN_U31jt5HgHBh7k3Grc5s4lw4ob-2Fr0yRdKsaHlSRHdR0SwB3KR7nD5ra5PLCuSKMFyMWOSVNZ25EYqr0028Prr7uwby-2FfIWCDzGQ20p8t539FVTvXo4Pm2VopMdyfdVOXH5xZbYSp1GdRCIGFMYoo3RfjxGbJcoaVh6cU-2F2SuUf9ZdMOPyQk7yCwZeytbpstd8L-2F9TRF-2Fv4mEArEytEzF45jOCIuojeaZwuhRmK5G9-2F-2BZfeH4Q-2B0poiDHkVCaBUsGT2FatMGMfSjbQpwFfX907rxnZ4q8eJEgLEKNVv1Ng-2BDN-2BzMV-2FZneNSZitCxSRSQXx6Jh-2BUA5BNk97IqkmFk6KcVcNW6Zq8yGdbEOFqCPmT9RIfk-2F0tIol6tEdPWGMHVjIfI3s20YmZkiX8-2FZEZjr-2BnX2PLR8RbFBs97yyO5fJkiBxTRYtac8r5PMJyFLyFN9W )

Questa è un’email generata automaticamente e non avremo la possibilità di leggere eventuali email di risposta. *Non rispondere a questo messaggio*.
Puoi contattarci cliccando *qui*. ( https://u15586970.ct.sendgrid.net/ls/click?upn=942-2F81YTq4FCz86XCgCDC7n6FPUYVAvWhlfN8foKeOSVu6jtJydf8w6VVROmoaoDoFq-_U31jt5HgHBh7k3Grc5s4lw4ob-2Fr0yRdKsaHlSRHdR0SwB3KR7nD5ra5PLCuSKMFyMWOSVNZ25EYqr0028Prr7uwby-2FfIWCDzGQ20p8t539FVTvXo4Pm2VopMdyfdVOXH5xZbYSp1GdRCIGFMYoo3RfjxGbJcoaVh6cU-2F2SuUf9ZdMOPyQk7yCwZeytbpstd8L-2F9TRF-2Fv4mEArEytEzF45jOCIuojeaZwuhRmK5G9-2F-2BZfeH4Q-2B0poiDHkVCaBUsGT2FatMGMfSjbQpwFfX907rxnZ4q8eJEgLEKNVv1Ng-2BDPCvAN7Iwc4Mfdqn-2FAXsR8LUImLF2kuqbG-2BlGpERuF6-2FWJaXqEf3GdWpS3XmJu5BnyeEJZND1sDb2G8QQv2skNUe3yqnLpYwdrvHnKPT8zGhOgnFbZPBLFWQpNkdib4P72Gtr7-2B-2B47prWmKLQX6LL2h )

*Grazie per averci letto!*
Copyright Together Price 2020 ©, All rights reserved.
