### ISSUE TITLE
MusicBrainz integration

### ISSUE THREAD

**Issue by waweic** [songlink/docs#2]
I would be rather interested in this feature as a lot of my music collection has MusicBrainz IDs attached and it would make it a whole lot easier to share. I would like to ask whether this is already envisioned or if there are major negative considerations about this

**Comment by kweiberth** [comment]
Hey @waweic, thanks for reaching out. This is already envisioned, though in the next few months we won't be working on adding new integrations to our automated matching. But MusicBrainz makes a lot of sense, there's been a few users who have asked for it and they seem to have a legit API, so we'll definitely be adding it at some point. 

If you'd like, can you send me an email to kurt @ song.link ? This way I can mark down your email with the MusicBrainz feature request and then we can make sure to keep you updated when we build it.
