### ISSUE TITLE
API Documentation Question

### ISSUE THREAD

**Issue by TylerAHolden** [songlink/docs#4]
I haven't tested but it would be nice to be able to hit an API endpoint with the song.link/i/{THIS_ID_HERE} to grab results. Is that ID always the default Itunes ID? 

Use case: Artist likes to have the song.link on hand and if they provide that, how can I use that ID to hit your API.

**Comment by kweiberth** [comment]
It's always the iTunes ID when the URL is /i/{ID_HERE}, where the /i/ denotes the service. So /s/{ID_HERE} would be a Spotify ID. Many Songlink URLs are /i/ bc our main search on our home page uses iTunes as the primary API. 

Your best bet though is to just pass in the entire Songlink URL as the url= param to the endpoint. We'll always (hopefully 😅) be able to parse our own URLs into the corresponding service + ID.

**Comment by TylerAHolden** [comment]
Ah I suppose I didn't think to try passing the songlink URL as the param!
